name: Contributors

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          round: true
          svgPath: CONTRIBUTORS.svg
